project:
  type: book
  output-dir: docs

book:
  title: "Diary"
  author: "Norah Jones"
  date: "3/12/2025"
  chapters:
    - index.qmd
    - Introduction.qmd
    - "Xaringan and Quarto.qmd"
    - Corrections.qmd
    - Policy.qmd
    - "Google Earth Engine I.qmd"
    - "Classification I.qmd"
    - "Classification II.qmd"
    -  SAR.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

